### ISSUE TITLE
pre-backup-lock/post-backup-unlock scripts are not idempotent

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/capi-release#140]
## Issue

pre-backup-lock/post-backup-unlock scripts are not idempotent.

## Context

If for whatever reason you have to run the scripts again if the instance is already locked/unlocked they will fail. 

## Steps to Reproduce

Run `bbr backup` and then `bbr backup-cleanup` - the latter will fail due to the api instance being already unlocked.

> Error attempting to run post-backup-unlock for job cloud_controller_ng on api/...

## Expected result

Running pre-backup-lock or post-backup-unlock should always succeed even if the respective state (instance being in maintenance mode or not) is already active.

## Current result

It fails if the instance is already in the desired state. 

## Possible Fix

Use the already existing `/var/vcap/data/cloud_controller_ng/tmp/proxy_temp/bbr_maintenance` "semaphore" file as indicator whether or not the instance is in the desired state is already (or employ a more sophisticated algorithm checking for the existence of the nginx maintenance process).

**Comment by tcdowney** [comment]
Thanks for reporting this @x6j8x!

The following two commits should fix this issue and will be available in the next capi-release:
* https://github.com/cloudfoundry/capi-release/commit/49d6977b829bd1dd39c7bed01743d8d23c31379b
* https://github.com/cloudfoundry/capi-release/commit/123bb4ca040a7161326fafa0c412af45d7ed1d23

Basically it just checks with `bpm list` to see if the `nginx_maintenance` job is already in the `stopped` state. Not super sophisticated, but gets the job done since `bpm` already knows how to track the lifecycle of the process.
