### ISSUE TITLE
yaml_escape is not defined in cc_deployment_updater

### ISSUE THREAD

**Issue by charleshansen** [cloudfoundry/capi-release#141]
Thanks for submitting an issue to `capi-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

The cc_deployment_updater job template is only valid if other templates have been compiled first. This is true during a normal deployment, but not in `bosh cck`

## Context

Noticed while looking at https://github.com/cloudfoundry/bosh/issues/2175

## Steps to Reproduce

In a cf-deployment, delete a scheduler VM in your IaaS console. (I was already at only 1 scheduler VM when I reproduced it)
Watch bosh scan-and-fix happen, you will get the errors in the linked issue `undefined method `yaml_escape'`
The error is from https://github.com/cloudfoundry/capi-release/blob/a85f6907722c1bba3c048eccef91a92e7a1846df/jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb#L38

## Expected result

bosh scan-and-fix can successfully recreate a scheduler VM

## Current result

scheduler VM is broken forever if you delete it

## Possible Fix

Define `yaml_escape` in all your templates
(e.g. https://github.com/cloudfoundry/capi-release/blob/a85f6907722c1bba3c048eccef91a92e7a1846df/jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb#L11-L18)

**Comment by voelzmo** [comment]
Out of curiosity: why did this work on initial deployment? Are we leaking functions (and other things, potentially) defined in one template into another? My understanding was that there each job gets its own isolated set of variables for rendering? I might be wrong here and this might even be intentional – not sure about this.

/cc @mfine @jfmyers9

**Comment by tcdowney** [comment]
This was fixed in https://github.com/cloudfoundry/capi-release/commit/cbb66b1c0212fd24a7578cd0d58769dce1d3ac81 and will ship with the next capi-release (1.81.0). @voelzmo you might want to reach out directly to @mfine @jfmyers9 and/or create a BOSH issue for those concerns since I don't think they are tracking this repo that closely.

**Comment by charleshansen** [comment]
Following up @voelzmo I created an issue in Bosh about the leaking functions.
