### ISSUE TITLE
Routes not mapping correctly with v3 docker apps + multi-app manifest

### ISSUE THREAD

**Issue by andy-paine** [cloudfoundry/capi-release#149]
## Issue

Routes do not map correctly for apps created with `v3-create-app --app-type docker` with multi-app manifests.

## Context

When creating apps with `v3-create-app --app-type docker` and trying to `v3-apply-manifest` & `v3-zdt-push`, the routes specified in the manifest appear to be bound (checking `cf routes` and `cf curl /v3/apps/$GUID/route_mappings` but they do not actually resolve (I assume they aren't actually correctly register by route registrar). Doing an explicit `cf map-route $APP $DOMAIN --hostname $HOST` for the exact same route that appears already bound fixes the issue. This does _not_ appear to happen for apps created with a lifecycle of `buildpack`

## Steps to Reproduce
With the following `manifest.yml` (ideally in a blank space with no routes):
```yml
---
applications:
  - name: app-1
    memory: 64M
    routes:
    - route: app-1-testing.$YOUR-DOMAIN
  - name: app-2
    memory: 64M
    routes:
    - route: app-2-testing.$YOUR-DOMAIN
```
1. Run `cf v3-create-app app-1 --app-type docker`
2. Run `cf v3-create-app app-2 --app-type docker`
3. Run `cf v3-apply-manifest -f manifest.yml`
4. Run `cf v3-zdt-push app-1 -o nginx:latest`
5. Run `cf v3-zdt-push app-2 -o nginx:latest`

## Expected result
Browsing to `https://app-1-testing.$YOUR-DOMAIN` should show the nginx homepage

## Current result
Browsing to `https://app-1-testing.$YOUR-DOMAIN` shows a 404 from CF.
The output of `cf routes` is:
```
space   host            domain                     port   path   type   apps    service
tmp     app-1-testing   $YOUR-DOMAIN                                    app-1
tmp     app-2-testing   $YOUR-DOMAIN                                    app-2
```
The output of `cf curl /v3/apps/$APP-1-GUID/route_mappings` includes:
```
resources": [
  {
    "guid": "e077d9da-fa33-4c63-9b64-42003e555eda",
    "created_at": "2019-07-20T10:09:49Z",
    "updated_at": "2019-07-20T10:09:49Z",
    "weight": 1,
    "links": {
      "self": {
        "href": "https://$CAPI_URL/v3/route_mappings/e077d9da-fa33-4c63-9b64-42003e555eda"
      },
      "app": {
        "href": "https://$CAPI_URL/v3/apps/$APP-1-GUID"
      },
      "route": {
        "href": "https://$CAPI_URL/v2/routes/0d64cc39-a6ce-44a4-93be-e6071335ec2f"
      },
      "process": {
        "href": "https://$CAPI_URL/v3/apps/d4036995-75a5-439a-9be2-a876e557ca66/processes/web"
      }
    }
  }
]
```
and `cf curl /v2/routes/0d64cc39-a6ce-44a4-93be-e6071335ec2f` (route from above mapping):
```
{
  "metadata": {
    "guid": "0d64cc39-a6ce-44a4-93be-e6071335ec2f",
    "url": "/v2/routes/0d64cc39-a6ce-44a4-93be-e6071335ec2f",
    "created_at": "2019-07-20T10:09:49Z",
    "updated_at": "2019-07-20T10:09:49Z"
  },
  "entity": {
    "host": "app-1-testing",
    "path": "",
    "domain_guid": "86484fb4-8d55-4f24-a3af-eda030b95ad8",
    "space_guid": "e0d602d6-49fa-4723-93bc-3ffc5c140831",
    "service_instance_guid": null,
    "port": null,
    "domain_url": "/v2/shared_domains/86484fb4-8d55-4f24-a3af-eda030b95ad8",
    "space_url": "/v2/spaces/e0d602d6-49fa-4723-93bc-3ffc5c140831",
    "apps_url": "/v2/routes/0d64cc39-a6ce-44a4-93be-e6071335ec2f/apps",
    "route_mappings_url": "/v2/routes/0d64cc39-a6ce-44a4-93be-e6071335ec2f/route_mappings"
  }
}
```
## Possible Fix
Not sure currently. Possibly related to route registrar.

**Comment by tcdowney** [comment]
Thanks for reporting this @andy-paine, you've uncovered a bug with the V3 `RouteMappingCreate` action _always_ setting the port on the route mapping to be `8080`.

https://github.com/cloudfoundry/cloud_controller_ng/blob/8879b7c3af0c8f87ed5fc4a9061313ce50f2d32d/app/actions/route_mapping_create.rb#L22

The routes _are_ created successfully and make their way to the desired LRP definition on Diego, but since the nginx Docker image listens on port `80` by default the route is pointing to the wrong place -- hence the 404.

The V2 version of `RouteMappingCreate` that gets hit when you do a regular `cf map-route` has special logic to handle the Docker app case:

https://github.com/cloudfoundry/cloud_controller_ng/blob/8879b7c3af0c8f87ed5fc4a9061313ce50f2d32d/app/actions/v2/route_mapping_create.rb#L72

This sets a sentinel value (`-1`) that causes us to use the port that the Docker image specifies in its execution metadata.

We're currently overhauling how route mappings work in V3 (e.g. deleting the `/v3/route_mappings` endpoint and introducing route [destinations](http://v3-apidocs.cloudfoundry.org/version/release-candidate/#insert-destinations-for-a-route)) and these appear to handle the port correctly for Docker apps:

https://github.com/cloudfoundry/cloud_controller_ng/blob/8879b7c3af0c8f87ed5fc4a9061313ce50f2d32d/app/actions/update_route_destinations.rb#L110-L114

We'll need to update our server-side app manifest logic and that should resolve this issue.

cc @reid47 @cunnie who have been working on Route Destinations recently.

**Comment by cunnie** [comment]
@tcdowney Our latest push did *not* fix the problem (we had hoped it would).

@andy-paine Thanks for a clear & succinct problem description.

**Comment by tcdowney** [comment]
@cunnie @piyalibanerjee 

https://github.com/cloudfoundry/cloud_controller_ng/commit/d9d951c09c711617d3a948ed6f0318bf6cae9cd5#diff-eceef0021a91ada80607d6edff8f60b2R38

I think if y'all just omit explicitly defaulting the port to `ProcessModel::DEFAULT_HTTP_PORT` in the code above it may just work.

**Comment by cunnie** [comment]
@andy-paine : we've submitted a fix: https://github.com/cloudfoundry/cloud_controller_ng/commit/6d2014885b0c8f1710a60e0d6169439397a375f5 , and we anticipate it clearing our Continuous Integration (CI) testing soon.

We're closing this ticket. Thanks again for an excellent problem description.

— @reid47 & @cunnie

**Comment by andy-paine** [comment]
That's brilliant - thanks for the quick fix :+1:
