### ISSUE TITLE
Bionic Support for NFS Mounter

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/capi-release#196]
## Issue

For convenience, we use NFS Mounter in a few places outside of the Cloud Controller and we've been upgrading those systems to Bionic. NFS Mounter (and obviously all of capi-release) doesn't support Bionic currently.

## Context

If you add NFS Mounter to an instance which uses the Bionic stemcell, the pre-start script doesn't even attempt to install the necessary Debian packages (See [pre-start.sh.erb lines 19-20](https://github.com/cloudfoundry/capi-release/blob/develop/jobs/nfs_mounter/templates/pre-start.sh.erb#L19-L20))

## Steps to Reproduce

1. Create an instance group which uses the bionic stemcell
2. Add the nfs-mounter job to the instance group
3. Deploy

## Expected result

I would expect to see nfs-common installed

## Current result

nfs-common (and other dependencies) are not installed and therefore nfs-mounter is unable to mount the share to the instance

## Possible Fix

Using apt-get I was able to temporarily add nfs-common to the VM. With nfs-common in place the NFS mounter was able to successfully mount my share. Here are the new deb versions that apt-get resolved:
```
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 keyutils amd64 1.5.9-9.2ubuntu2 [47.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 libevent-2.1-6 amd64 2.1.8-stable-4build1 [133 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 libnfsidmap2 amd64 0.25-5.1 [27.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 rpcbind amd64 0.2.3-0.6ubuntu0.18.04.1 [42.0 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 nfs-common amd64 1:1.3.4-2.1ubuntu5.3 [206 kB]
```

**Comment by jriguera** [comment]
We have the same issue, so we have decided to decouple the _nfs_mounter_ job  from CAPI and create a release only for dealing with nfs mountpoints. Also the release uses APT to install the dependencies, instead of including the deb packages there (it needs internet access), and if a version is specified, holds them.  See https://github.com/SpringerPE/nfsclient-boshrelease

**Comment by slcardinal** [comment]
Is there any movement on getting this issue resolved? We are updating our Cloud Foundry deployment to the Bionic stemcell and this issue is holding us up. We are looking at using the workaround mentioned in the comment by @jriguera. It would be nice if this worked as it did with the Xenial stem cell.

**Comment by moleske** [comment]
Are you using [capi release 1.129.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.129.0)?  That added the bionic blobs for nfs

**Comment by slcardinal** [comment]
@moleske, I was not, I was using 1.128.0. While doing research on this issue, I discovered that 1.129.0 had a fix for this problem. I have updated my deployment to use capi-rlease 1.129.0. Testing at this very moment. Thanks for following up.
