### ISSUE TITLE
Rotating `internal_api_password` while pushing breaks an application for a while

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry/capi-release#59]
## Issue

While rotating `internal_api_password` some application may end up in a 'corrupted/non-recoverable' state for a while.

## Context

We tried to change `internal_api_password`, deploy cf and then diego while continuously pushing a sample application.
A push was in progress while cf was being updated and the push started to hang. After some time we interrupted the push command.
The next push failed due to `Error restarting application: Server error, status code: 400, error code: 100001, message: The app is invalid: VCAP::CloudController::BuildCreate::StagingInProgress`. 
We tried to delete the app then, but we got the error `Server error, status code: 500, error code: 10011, message: Database error`.

## Steps to Reproduce

- Run the following command in an endless loop
```
timeout 180 cf push APP_NAME
```

- Modify  [internal_api_password](https://github.com/cloudfoundry/cf-release/blob/8bd6495a0da22a82dc96a09c231e44ad23442b48/templates/cf.yml#L749)

- Deploy cf
- Deploy diego

## Expected result

Application lifecycle should work for all applications after the cf and diego deployment.

## Current result

After diego is deployed, applications lifecycle works again for apps that have been *not* pushed during the cf deployment.
Apps pushed during cf deployment will be in the described state. I don't know if the user can fix the application or not. 

After some time (I retried the next day), some timeout probably kicked in  and I was able to delete the broken app.

## Possible Fix

No concrete idea, maybe some improvement in error handling / rollback action in the push handling.

**Comment by Gerg** [comment]
@tyyko We have recently completed a track of work to change CC <-> Diego communication to use mutual-TLS instead of basic auth credentials. Details [here](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/V3L5ZYIELIKYT73OFXEJWXUMKRLDL3IS/).

This should enable downtime-less cred rotation as follows:
1. Add an additional, new CA to both Diego and CC
2. Deploy both
3. Remove the old CA

Check it out and let us know if it works for you.

Thanks,
Greg

**Comment by tyyko** [comment]
Hi Greg, thanks for your reply! 

We are about to enable the new way of communication but when I did the rotation test I missed to remember that the basic auth credential would be deprecated, sorry.

Does it make sense to remove the property [1] from the CF manifest (and the CC spec) as well or is it not yet enforced on CF v276? 

Thanks and regards,
Michael

[1] https://github.com/cloudfoundry/cf-release/blob/v276/templates/cf.yml#L745

**Comment by ljfranklin** [comment]
@tyyko as the mTLS migration is fairly involved, we've kept the old properties around for now to give operators a large window to migrate. At some point in the future we'll send out a warning email to cf-dev mailing list and remove the pre-mTLS properties.

Are you okay with closing out this issue?

**Comment by tyyko** [comment]
Sure, thanks for the explanation!

**Comment by michaelgrifalconi** [comment]
Hello, I still see [the property on cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1207), could you give an update on the plans to remove it?
Thanks!

**Comment by cwlbraa** [comment]
@Gerg @tcdowney you know if the deprecation notice was ever sent? 

cf-d definitely still sets the password field all over the place, but it's a bit redundant since that communication path  is also mTLS-equipped.

https://github.com/cloudfoundry/cf-deployment/blob/888f31de6708e4a3afc068ec02eaca5a4a4b6657/cf-deployment.yml#L1153

**Comment by selzoc** [comment]
@michaelgrifalconi here is the PR to cf-d to remove this property: https://github.com/cloudfoundry/cf-deployment/pull/861

Thanks for following this issue for years! 😄
