### ISSUE TITLE
Unknown Error Has Occurred When Running CATS 

### ISSUE THREAD

**Issue by joshzarrabi** [cloudfoundry/capi-release#78]
## Issue

When running CATS we get the following failure:
```
[2018-02-21 20:05:21.32 (UTC)]> cf delete-buildpack CATS-7-BPK-f7686884-77b3-4bd6-6 -f 
Deleting buildpack CATS-7-BPK-f7686884-77b3-4bd6-6...
FAILED
Error deleting buildpack CATS-7-BPK-f7686884-77b3-4bd6-6
An unknown error occurred.
```

## Context

capi-release 1.28.0 (but noticed this with other versions)
multi-node galera mysql cluster

## Steps to Reproduce

Deploy CF with mult-node galera mysql cluster and run cats (8 ginkgo nodes)

## Expected result

CATs pass

## Current result

We've seen CATS fail many times with this same error but while running many different commands. It is a flake and if we rerun the tests they pass.

The cloud_controller_worker logs indicate that the mysql server has `gone away`.
https://gist.github.com/joshzarrabi/bd37c23bd7b5a3e0a064f1eeab28b80d

We x-team paired with the mysql team and they showed us logs that indicate if the mysql proxies switched nodes. About 2000s (30m) before the error occurred, the proxies did switch nodes.

Furthermore, we queried the open connections to the database and noticed that there were many, long-running (~4000s) connections to the database. We think there might be an issue with cloud_controller_worker not properly noticing connections changes (ref https://github.com/jeremyevans/sequel/issues/368#issuecomment-316171012).

## Possible Fix

 We are curious if you're configuring this value to validate connections (http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html).

cc @kkallday @APShirley @ndhanushkodi

**Comment by kkallday** [comment]
@joshzarrabi and I spoke with @Gerg and @selzoc and were told that this isn't a problem that other community teams have run into because they are either (1) not deploying CF with multi-node cf-mysql (https://github.com/cloudfoundry/cf-mysql-release) or (2) using an external DB such as Amazon RDS, Google CloudSQL, etc.

Given the frequency that our team is seeing this issue, we have reason to believe that deployments with multiple mysql nodes are prone to this issue. Furthermore, after speaking with @apshirley and @ndhanushkodi it seems like this issue might be related to `cloud_controller_worker`'s mysql connections not reconnecting when the mysql proxies switch to a new master node. The post above has a link to a feature in the `Sequel` library, used by the cc workers, that might be useful.

**Comment by ljfranklin** [comment]
Searching through build logs I don't think we've seen this error in the last 30 days. Going to close this out for now but will re-open if we start seeing it again.

**Comment by selzoc** [comment]
OK!
